# Generated by Django 3.1.2 on 2021-01-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500, verbose_name='NATURE ACTIVITE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'activite',
                'verbose_name_plural': 'ACTIVITES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accronyme', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=500)),
                ('annee', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Année')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'CAMPAGNES',
                'ordering': ['accronyme'],
            },
        ),
        migrations.CreateModel(
            name='Cat_Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'categorie plant',
                'verbose_name_plural': 'CATEGORIES PLANTS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='CODE PAYS')),
                ('pays', models.CharField(max_length=255, verbose_name='PAYS')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'origine',
                'verbose_name_plural': 'ORIGINES',
                'ordering': ['pays'],
            },
        ),
        migrations.CreateModel(
            name='Pepiniere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicien', models.CharField(max_length=255, verbose_name='NOM ET PRENOMS TECHNICIEN')),
                ('localisation', models.CharField(max_length=255, verbose_name='LOCALITE (S/P - VILLAGE)')),
                ('total_semance', models.PositiveIntegerField(default=0, verbose_name='QTE TOTAL SEMANCE RECU')),
                ('total_sachet', models.PositiveIntegerField(default=0, verbose_name='QTE TOTAL SACHET RECU')),
                ('sachet_rempli', models.PositiveIntegerField(default=0, verbose_name='QTE TOTAL SACHET REMPLI')),
                ('sachet_perdu', models.PositiveIntegerField(default=0, verbose_name='QTE TOTAL SACHET PERDU')),
                ('plant_mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANT MATURE')),
                ('plant_retire', models.PositiveIntegerField(default=0, verbose_name='NBRE TOTAL PLANT RETIRE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pépinière',
                'verbose_name_plural': 'PEPINIERES',
            },
        ),
        migrations.CreateModel(
            name='Projet_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500, verbose_name='CATEGORIE PROJET')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catégorie projet',
                'verbose_name_plural': 'CATEGORIES PROJETS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'REGIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Sous_Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sous prefecture',
                'verbose_name_plural': 'SOUS PREFECTURES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accronyme', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=500)),
                ('chef', models.CharField(max_length=255)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('etat', models.CharField(choices=[('en_cours', 'EN COURS'), ('suspendu', 'SUSPENDU'), ('traite', 'TRAITE')], max_length=50)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet_cat', verbose_name='CATEGORIE PROJET')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'PROJETS',
                'ordering': ['accronyme'],
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(choices=[('ANACARDE', 'ANACARDE'), ('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('COTON', 'COTON'), ('HEVEA', 'HEVEA'), ('PALMIER', 'PALMIER A HUILE')], max_length=150)),
                ('certification', models.CharField(choices=[('UTZ', 'UTZ'), ('RA', 'RA'), ('BIO', 'BIO'), ('PROJET', 'PROJET')], max_length=150)),
                ('prix', models.PositiveIntegerField(default=100, verbose_name='Prix/Kg')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
            ],
            options={
                'verbose_name': 'prime',
                'verbose_name_plural': 'PRIMES',
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accronyme', models.CharField(max_length=250, verbose_name='NOM SCIENTIFIQUE')),
                ('libelle', models.CharField(max_length=250, verbose_name='NOM USUEL')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cat_plant')),
            ],
            options={
                'verbose_name': 'espece',
                'verbose_name_plural': 'ESPECES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Detail_Retrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=250, verbose_name='DESTINATION')),
                ('plant_retire', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANT RETIRE')),
                ('date', models.DateField(verbose_name='DATE RETRAIT')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.pepiniere')),
            ],
            options={
                'verbose_name': 'retrait plant',
                'verbose_name_plural': 'RETRAITS PLANTS',
            },
        ),
        migrations.CreateModel(
            name='Detail_Pepiniere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_recu', models.PositiveIntegerField(default=0, verbose_name='QTE RECU')),
                ('date', models.DateField(verbose_name='DATE RECEPTION')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece_recu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.pepiniere')),
            ],
            options={
                'verbose_name': 'détails plants reçus',
                'verbose_name_plural': 'DETAILS SEMANCE RECUS',
            },
        ),
    ]
