# Generated by Django 3.1.2 on 2021-01-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepiniere',
            name='contacts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
