# Generated by Django 3.1.2 on 2021-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_pepiniere_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepiniere',
            name='total_semance',
            field=models.PositiveIntegerField(default=0, verbose_name='QTE TOTAL SEMENCE RECU'),
        ),
    ]
