# Generated by Django 3.1.2 on 2021-01-08 11:23

import communaute.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('chocolotiers', '0001_initial'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='NOM COMMUNAUTE')),
                ('responsable', models.CharField(max_length=255, verbose_name='NOM ET PRENOMS RESPONSABLE')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('culture_associee', models.CharField(choices=[('banane', 'BANANE'), ('mais', 'MAIS'), ('coton', 'COTON'), ('coton', 'COTON')], max_length=50, verbose_name='CULTURE ASSOCIEE')),
                ('logo', models.ImageField(blank=True, upload_to=communaute.models.upload_logo_site, verbose_name='Logo')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chocolotiers.client')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
                ('projet', models.ManyToManyField(to='parametres.Projet')),
            ],
            options={
                'verbose_name': 'Communaute',
                'verbose_name_plural': 'COMMUNAUTE',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='LE CODE PARCELLE EST GENERE AUTOMATIQUEMENT', max_length=150, null=True, verbose_name='CODE PARCELLE')),
                ('acquisition', models.CharField(choices=[('heritage', 'HERITAGE'), ('achat', 'ACHAT'), ('autres', 'AUTRES')], max_length=50, verbose_name='MODE ACQUISITION')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('superficie', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('culture', models.CharField(choices=[('anacarde', 'ANACARDE'), ('cacao', 'CACAO'), ('cafe', 'CAFE'), ('coton', 'COTON'), ('hevea', 'HEVEA'), ('palmier', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('autre', 'AUTRES')], max_length=50, verbose_name='CULTURE')),
                ('certification', models.CharField(choices=[('utz', 'UTZ'), ('ra', 'RA'), ('bio', 'BIO'), ('projet', 'PROJET'), ('autre', 'PROJET')], max_length=50, verbose_name='CERTIFICATION')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelle_communautaire', to='communaute.communaute')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'PARCELLE',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plant', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communaute.parcelle')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_communautaire', to='parametres.projet')),
            ],
            options={
                'verbose_name': 'planting',
                'verbose_name_plural': 'PLANTINGS',
            },
        ),
        migrations.CreateModel(
            name='Details_planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plante', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS PLANTE')),
                ('remplace', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS REMPLACES')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MATURE')),
                ('observation', models.TextField(blank=True, null=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_planting_communautaire', to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communaute.planting')),
            ],
        ),
    ]
