# Generated by Django 3.1.2 on 2021-01-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='acquisition',
            field=models.CharField(choices=[('heritage', 'HERITAGE'), ('achat', 'ACHAT'), ('autres', 'AUTRES')], default='heritage', max_length=50, verbose_name='MODE ACQUISITION'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='certification',
            field=models.CharField(choices=[('utz', 'UTZ'), ('ra', 'RA'), ('bio', 'BIO'), ('projet', 'PROJET'), ('autre', 'PROJET')], default='utz', max_length=50, verbose_name='CERTIFICATION'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='culture',
            field=models.CharField(choices=[('anacarde', 'ANACARDE'), ('cacao', 'CACAO'), ('cafe', 'CAFE'), ('coton', 'COTON'), ('hevea', 'HEVEA'), ('palmier', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('autre', 'AUTRES')], default='cacao', max_length=50, verbose_name='CULTURE'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CODE PRODUCTEUR'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='cooperative',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='genre',
            field=models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], default='H', max_length=2),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenoms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='type_producteur',
            field=models.CharField(choices=[('membre', 'MEMBRE'), ('usager', 'USAGER')], default='membre', max_length=50, verbose_name='TYPE PRODUCTEUR'),
        ),
    ]
