# Generated by Django 3.1.2 on 2021-01-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_auto_20210113_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative'),
        ),
    ]
