# Generated by Django 3.1.2 on 2021-01-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('cooperatives', '0004_auto_20210113_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producteur',
            name='add_le',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='update_le',
        ),
        migrations.AlterField(
            model_name='producteur',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='origine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.origine'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='sous_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.sous_prefecture'),
        ),
    ]
