# Generated by Django 3.1.2 on 2021-01-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_auto_20210113_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='add_le',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='update_le',
        ),
    ]
