# Generated by Django 3.1.2 on 2021-01-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_auto_20210113_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details_planting',
            options={'verbose_name': 'detail planting', 'verbose_name_plural': 'DETAILS PLANTING'},
        ),
    ]
