# Generated by Django 3.1.2 on 2021-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0008_auto_20210122_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='participant',
        ),
        migrations.AddField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(to='cooperatives.Producteur'),
        ),
    ]
