# Generated by Django 3.1.2 on 2021-01-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0009_auto_20210122_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='copperative',
            new_name='cooperative',
        ),
    ]
